# Basic data types for image.

image_size:
  type: mapping
  constraints:
    FullyValidatable: ~
  mapping:
    width:
      type: integer
      label: 'Width'
      nullable: true
      constraints:
        NotBlank:
          allowNull: true
    height:
      type: integer
      label: 'Height'
      nullable: true
      constraints:
        NotBlank:
          allowNull: true

field_default_image:
  type: mapping
  mapping:
    uuid:
      type: uuid
    alt:
      type: label
      label: 'Alternative text'
    title:
      type: label
      label: 'Title'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
