<?php

/**
 * @file
 * Hooks related to klaro__testing.
 */

/**
 * Load all stages into theme.registry.
 */
function klaro__testing_theme($existing, $type, $theme, $path) {
  $stages_path = $path . '/templates';

  $items = [];
  foreach (scandir($stages_path) as $stage) {
    $stage_name = basename($stage, '.html.twig');
    if (empty($stage_name) || $stage_name == "." || $stage_name == "..") {
      continue;
    }
    // POC this should be replaceable with theme suggestions.
    $items['STAGE__' . $stage_name] = [
      'render element' => 'children',
      'template' => $stage_name,
      'path' => $stages_path,
    ];
  }
  return $items;
}
