ai_provider_openai.settings:
  type: config_object
  label: 'OpenAI Settings'
  mapping:
    api_key:
      type: string
      label: 'The API key for OpenAI via Key module'
    moderation:
      type: boolean
      label: 'Enable moderation requests before each request.'
    host:
      type: string
      label: 'The host to use for the API requests.'
