<?php

/**
 * @file
 * The module file for anrt_entity_browsers.
 */

/**
 * Implements hook_preprocess_views_view().
 */
function anrt_entity_browsers_preprocess_views_view(&$variables) {
  $anrt_entity_browsers = [
    'media_browser_image',
    'media_browser_tweets',
    'media_browser_video',
    'media_browser_files',
  ];
  if (in_array($variables['view']->id(), $anrt_entity_browsers)) {
    $variables['view_array']['#attached']['library'][] = 'media_entity_browser/view';
  }
}
