ai_translate.settings:
  type: config_object
  label: 'AI Translate settings'
  mapping:
    reference_defaults:
      type: ignore # Weird mix.
      label: reference_defaults
    prompt:
      type: string
      label: Prompt
      description: 'The prompt being used'
