<?php

/**
 * @file
 * Contains entity_usage_test.module.
 */

/**
 * Implements hook_entity_usage_block_tracking().
 */
function entity_usage_test_entity_usage_block_tracking(string $target_id, string $target_type, string $source_id, string $source_type, string $source_langcode, string $source_vid, string $method, string $field_name, string $count) {
  if ($count == 31) {
    return TRUE;
  }
  return FALSE;
}
