<?php

/**
 * @file
 * Provides hook implementations for the AI Chatbot module.
 */

/**
 * Implements hook_theme().
 */
function ai_chatbot_theme() {
  return [
    'ai_chatbot' => [
      'variables' => [
        'header' => '',
        'rendered_form' => '',
        'messages' => [],
      ],
    ],
    'ai_chatbot_message' => [
      'variables' => [
        'message' => [],
        'username' => 'Chatbot',
        'timestamp' => '',
        'bot_image' => '',
      ],
    ],
  ];
}

/**
 * Implements preprocess function for ai_chatbot_message theme.
 */
function template_preprocess_ai_chatbot_message(&$variables) {

}
