<?php
/**
 * @file Module file to output nodes as JSON
 */

/**
 * Implements hook_menu().
 */
function json_node_menu() {
  $items['node/%node/json'] = array(
    'page callback' => 'json_node_endpoint',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
  );
  return $items;
}

// Output each node as a JSON object
function json_node_endpoint($node) {
  drupal_json_output($node);
}
