include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  _TARGET_DRUPAL: 11.0
  _TARGET_PHP: 8.3
  _PHPUNIT_EXTRA: --verbose
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  OPT_IN_TEST_PREVIOUS_MINOR: 0
  OPT_IN_TEST_NEXT_MINOR: 1
  #OPT_IN_TEST_NEXT_MAJOR: 1
  OPT_IN_TEST_MAX_PHP: 1
  _PHPUNIT_CONCURRENT: 1
  SKIP_ESLINT: 1
  # showdown.js is full of emoji words.
  _CSPELL_IGNORE_PATHS: "'modules/ai_chatbot/js', '.cspell-project-words.txt'"

pages:
  stage: .post
  before_script:
    - python docs/build-docs.py

cspell:
  allow_failure: false
stylelint:
  allow_failure: false
phpcs:
  allow_failure: false
phpstan:
  allow_failure: false
  before_script:
    - composer require --dev drush/drush

