<?php

/**
 * @file
 * Create global variables to be printed in any template like so {{ variable }}.
 *
 * Table of Contents.
 * 1) Paths
 * 1.1) Current Path - {{ global_variables.current_path }}
 * 1.2) Base URL - {{ global_variables.base_url }}
 * 2) Current Page Title {{ global_variables.current_page_title }}
 * 3) Site Information Page Global variables
 * 3.1) Site Name - {{ global_variables.site_name }}
 * 3.2) Site Slogan - {{ global_variables.site_slogan }}
 * 3.3) Site Mail - {{ global_variables.site_mail }}
 * 3.4) Site Logo - {{ global_variables.logo }}
 * 4) Social Sharing
 * 4.1) Twitter - {{ global_variables.social_sharing.twitter }}
 * 4.2) Facebook - {{ global_variables.social_sharing.facebook }}
 * 4.3) LinkedIn - {{ global_variables.social_sharing.linkedin }}
 * 4.4) Email - {{ global_variables.social_sharing.email }}
 */

use Drupal\Core\Url;
use Symfony\Cmf\Component\Routing\RouteObjectInterface;

/**
 * Implements hook_template_preprocess_default_variables_alter().
 */
function mgv_template_preprocess_default_variables_alter(&$variables) {
  // Print the current path. This could be useful if you want to do a redirect
  // after a form is submitted, e.g. ?destination={{ current_path }}.
  $current_path = \Drupal::service('path.current')->getPath();
  $variables['global_variables']['current_path'] = $current_path;

  // Print the Base URL - for example, if you need to construct a link to share
  // on social media.
  global $base_url;
  $variables['global_variables']['base_url'] = $base_url;

  // Print the current page's title. This could be useful if you want to add
  // the current page title as a breadcrumb.
  $request = \Drupal::request();
  if ($route = $request->attributes->get(RouteObjectInterface::ROUTE_OBJECT)) {
    $variables['global_variables']['current_page_title'] = \Drupal::service('title_resolver')->getTitle($request, $route);
  }

  // Site Information Page Global Variables.
  //
  // Print the Site Name. For example, you might want to have a
  // Copyright "My Site Name" message in the footer.
  $config_system_site = \Drupal::config('system.site');
  $variables['global_variables']['site_name'] = $config_system_site->get('name');

  // Print the Site Slogan.
  $variables['global_variables']['site_slogan'] = $config_system_site->get('slogan');

  // Print the Site Email.
  $variables['global_variables']['site_mail'] = $config_system_site->get('mail');

  // Print the Site logo's URL. - we are only printing the URL so you can add
  // custom alt (and other) attributes to the image if you wish.
  $theme_name = \Drupal::theme()->getActiveTheme()->getName();
  $variables['global_variables']['logo'] = theme_get_setting('logo.url', $theme_name);

  // Social Sharing
  include 'includes/social-sharing.php';
}
