<?php

/**
 * @file
 * Create global variables to be printed in any template like so {{ variable }}.
 *
 * Table of Contents.
 * 1) Paths
 * 1.1) Current Path - {{ global_variables.current_path }}
 * 1.2) Base URL - {{ global_variables.base_url }}
 * 2) Current Items
 * 2.1) Current Page Title {{ global_variables.current_page_title }}
 * 2.2) Current Langcode {{ global_variables.current_langcode }}
 * 2.3) Current Langname {{ global_variables.current_langname }}
 * 3) Site Information Page Global variables
 * 3.1) Site Name - {{ global_variables.site_name }}
 * 3.2) Site Slogan - {{ global_variables.site_slogan }}
 * 3.3) Site Mail - {{ global_variables.site_mail }}
 * 3.4) Site Logo - {{ global_variables.logo }}
 * 4) Social Sharing
 * 4.1) Twitter - {{ global_variables.social_sharing.twitter }}
 * 4.2) Facebook - {{ global_variables.social_sharing.facebook }}
 * 4.3) LinkedIn - {{ global_variables.social_sharing.linkedin }}
 * 4.4) Email - {{ global_variables.social_sharing.email }}
 */

/**
 * Implements hook_template_preprocess_default_variables_alter().
 */
function mgv_template_preprocess_default_variables_alter(&$variables) {
  /* @var \Drupal\mgv\MgvPluginManager $variables_manager */
  $variables_manager = \Drupal::service('plugin.manager.mgv');
  $variables['global_variables'] = $variables_manager->getVariables();
}
