<?php

/**
 * @file
 * A module file.
 */

use Drupal\ai_ckeditor\Hook\AiCKEditorHooks;
use Drupal\ai_ckeditor\PreRender\PreRender;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;

/**
 * Implements hook_element_info_alter().
 */
function ai_ckeditor_element_info_alter(array &$info): void {
  if (isset($info['text_format']['#pre_render'])) {
    $info['text_format']['#pre_render'][] = [
      PreRender::class,
      'textFormatPreRender',
    ];
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function ai_ckeditor_module_implements_alter(&$implementations, $hook): void {
  if (isset($implementations['ai_ckeditor'])) {
    $implementation = $implementations['ai_ckeditor'];
    unset($implementations['ai_ckeditor']);
    $implementations['ai_ckeditor'] = $implementation;
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for system_modules_uninstall_confirm_form.
 */
#[LegacyHook]
function ai_ckeditor_form_system_modules_uninstall_confirm_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  \Drupal::service(AiCKEditorHooks::class)->formSystemModulesUninstallConfirmFormAlter($form, $form_id, $form_state);
}
