# Schema for the configuration files of the Dropai provider module.
dropai_provider.settings:
  type: config_object
  label: 'Dropai provider settings'
  mapping:
    example:
      type: string
      label: 'Example'
