ai_content.settings:
  type: config_object
  label: AI Automator
  mapping:
    analyse_policies_enabled:
      type: string
      label: 'Choose AI Content Analysis model'
      required: false
    tone_adjust_enabled:
      type: string
      label: 'Choose AI Content Tone Adjustment model'
      required: false
    summarise_enabled:
      type: string
      label: 'Choose AI Content Summarisation model'
      required: false
    suggest_title_enabled:
      type: string
      label: 'Choose AI Content Title Suggestion model'
      required: false
    suggest_tax_enabled:
      type: string
      label: 'Choose AI Content Taxonomy Suggestion model'
      required: false
