<?php

/**
 * @file
 * AI Search module file.
 */

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\ai_search\Plugin\search_api\processor\DatabaseBoostByAiSearch;
use Drupal\search_api\IndexInterface;

/**
 * Implements hook_entity_type_alter().
 */
function ai_search_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['search_api_index'])) {
    /** @var \Drupal\Core\Config\Entity\ConfigEntityTypeInterface $entity_type */
    $entity_type = $entity_types['search_api_index'];
    $entity_type->setFormClass('fields', 'Drupal\ai_search\Form\AiSearchIndexFieldsForm');
  }
}

/**
 * Implements hook_query_TAG_alter().
 */
function ai_search_query_search_api_db_search_alter(AlterableInterface $query) {
  DatabaseBoostByAiSearch::queryAlter($query);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function ai_search_search_api_index_delete(EntityInterface $entity) {
  if ($entity instanceof IndexInterface) {
    $config_factory = \Drupal::configFactory();
    if ($config = $config_factory->getEditable('ai_search.index.' . $entity->id())) {
      $config->delete();
    }
  }
}

/**
 * Implements hook_preprocess_search_api_index().
 */
function ai_search_preprocess_search_api_index(array &$variables) {
  // Get the index.
  /** @var \Drupal\search_api\IndexInterface $index */
  $index = $variables['index'];
  $backend = $index->hasValidServer() ? $index->getServerInstance()->getBackendId() : NULL;
  if (
    $backend === 'search_api_ai_search'
    && !empty($variables['table']['#rows'])
  ) {
    foreach ($variables['table']['#rows'] as $key => $row) {
      if (
        !isset($row['data'][0]['data'])
        || (string) $row['data'][0]['data'] !== (string) t('Server index status')
      ) {
        continue;
      }

      $variables['table']['#rows'][$key]['data'][1] = t('This statistic normally counts the rows of data in your actual index by querying your database with no filters. Vector databases require a vector to compare against so that approach does not work here. Please see the Search API Server "View" page to check on the status of your connection in general.');
    }
  }
}
