<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * This is a small module to make the D8 node edit page more like the D7 verion.
 */

/**
 * Implements hook_preprocess_page().
 */
function seven_ui_preprocess_page(&$variables) {
  if (\Drupal::theme()->getActiveTheme()->getName() == 'seven') {
    $variables['#attached']['library'][] = 'seven_ui/seven_ui';
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function seven_ui_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'media_entity_browser') {
    $variables['view_array']['#attached']['library'][] = 'seven_ui/media-entity-browser-overrides';
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 * Add extra languages for CodeSnippet 
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */
function seven_ui_form_filter_format_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['editor']['settings']['subform']['plugins']['codesnippet'])) {
    $form['editor']['settings']['subform']['plugins']['codesnippet']['highlight_languages']['#options']['twig'] = 'Twig';
    asort($form['editor']['settings']['subform']['plugins']['codesnippet']['highlight_languages']['#options']);
  }
}

  